### ISSUE TITLE
Mixed content error with admin interface, osm, and https

### ISSUE THREAD

**Issue by amd77** [caioariede/django-location-field#142]
If you browse the admin interface using https:// with openstreetmap provider, browser fails to load images because of "mixed content" (osm images are linked using http://).

One solution could be replacing all ocurrences of "https://" and "http://" with "//" so the web should be browsable using http (debugging using runserver) and https (production deployment). For example, in this file: static/location_field/js/form.js (line 355)

Double check if tile provider provides both protocols.

**Comment by wolfskaempf** [comment]
As far as I can tell this is already fixed in this repository's master branch (see https://github.com/caioariede/django-location-field/pull/121) but no new release was pushed to PyPi since then. 

@caioariede If you released the current state of the repo as a new version on PyPi, this would fix this and other issues. Let me know if I can help you with that! Thank you! ⭐

**Comment by caioariede** [comment]
A new version has been released
